### ISSUE TITLE
Unable to bgzip fastq file with bgzf.py

### ISSUE THREAD

**Issue by jenzopr** [conda-forge/biopython-feedstock#6]
Hi Peter,

I was trying to block-access a FASTQ file for multi-cored demultiplexing. 
The documentation of bgzf.py gives a hint on how to produce a bgzip'ed file:
`bgzf.py < test.fastq > test.fastq.bgz`
When I do this, I get an type error:
```
Producing BGZF output from stdin...
Traceback (most recent call last):
  File "/home/jens/miniconda3/envs/sc-preprocess/lib/python3.5/site-packages/Bio/bgzf.py", line 874, in <module>
    w.write(data)
  File "/home/jens/miniconda3/envs/sc-preprocess/lib/python3.5/site-packages/Bio/bgzf.py", line 801, in write
    self._write_block(self._buffer[:65536])
  File "/home/jens/miniconda3/envs/sc-preprocess/lib/python3.5/site-packages/Bio/bgzf.py", line 785, in _write_block
    self._handle.write(data)
TypeError: write() argument must be str, not bytes
```

Just FYI: I tried before with htslib (`bgzip`), but it seems that `bgzip` does not produce the `_bgzf_magic` string - which is why reading a `bgzip`'ed file fails with
```
for values in bgzf.BgzfBlocks(h, "rb"):
...   print("Raw start %i, raw length %i; data start %i, data length %i" % values)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jens/miniconda3/envs/sc-preprocess/lib/python3.5/site-packages/Bio/bgzf.py", line 400, in BgzfBlocks
    block_length, data = _load_bgzf_block(handle)
  File "/home/jens/miniconda3/envs/sc-preprocess/lib/python3.5/site-packages/Bio/bgzf.py", line 415, in _load_bgzf_block
    % (_bgzf_magic, magic, handle.tell()))
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not '@NS5'; handle.tell() now says 4
```

Any idea what I'm doing wrong? 
Best and thanks,
Jens

Edit: Maybe also @bgruening @cbrueffer

**Comment by peterjc** [comment]
This is not a bug in the conda-forge recipe, it looks like a bug in Biopython itself - could re file an issue here please:

https://github.com/biopython/biopython/issues

I suspect the problem is running ``bgzf.py`` may only have been tested under Python 2, and not Python 3.

**Comment by jenzopr** [comment]
Thanks Peter!
